name: CI/CD Pipeline for Keycloak Deployment

on:
  push:
    branches:
      - main  # Trigger the pipeline when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v4.2.0

      # Step 2: Install Docker
      - name: Install Docker
        uses: docker/setup-docker@v2  # Set up Docker environment

      # Step 3: Pull Keycloak Docker image and start Keycloak container
      - name: Run Keycloak container
        run: |
          docker run -d \
            --name keycloak \
            -e KEYCLOAK_USER=admin \
            -e KEYCLOAK_PASSWORD=admin_password \
            -p 8080:8080 \
            quay.io/keycloak/keycloak:22.0.3

      # Step 4: Set up Ansible
      - name: Setup Ansible
        uses: alex-oleshkevich/setup-ansible@v1.0.1

      # Step 5: Run Ansible Playbook to configure Keycloak and import realm configuration
      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v2.8.0
        with:
          playbook: ansible-implementation.yml  # Your Ansible playbook to configure Keycloak


